Feat/add deployment scripts
latteswap-official/latteswap-contract pull request #3
Opened 2021-07-11 13:21 UTC by mint-chocolate-frappuccino

## Description
This is a PR containing
- adding/altering deployment scripts for
   - adding LatteVault deployment on 001
   - adding addLiquidity (003) deployment script
   - adding an ownership transfer to TimeLock deployment script
   - adding a deployment script for adding a master barista pool
- add more unit tests on LatteSwapRouter
- remove admin modifier since it's redundant with an `owner` role
## Purpose of this change
- to fulfill an AMM flow and ensure that no defects detected
## Is this PR Breaking Changes?
- [ ] Y
- [x] N
## Changes:
- chore: add solidity settings
- refactor: remove onlyAdmin modifier since it's kinda redundant
- chore: add LatteVault deployment on master barista deployment script
- chore: add addLiquidity deployment script for adding an initial liquidity
- chore: add transfer ownership to TimeLock deployment script
- chore: add a deployment script for adding a pool to master barista
- test: rename a test description for latte swap factory test
- test: makes chainID as an injected param rather than 1 which is hard-code
- test: add a unit test for latte swap router
- chore: update package json
- chore: add script command for s000, s001

2021-07-12 04:45 UTC, coco-coke-kub requested changes

2021-07-12 04:45 UTC, coco-coke-kub commented on deploy/001_deploy_master_barista.ts
> +  // LatteVault
Separate `LatteVault` to another deployment script. We won't launch it at Genesis.

2021-07-12 04:45 UTC, coco-coke-kub commented on deploy/S001_timelock_add_pool_to_master_barista.ts
> +  if (!verifyStakingTokenAddress(allAvailableStakingToken, STAKING_TOKEN_ADDRESS)) throw new Error('verifyStakingTokenAddress:: not found')
verify like this won't work as there can be 1,000++ LPs and I don't think we will add all of them in `config.LpTokens`. I think can leave it out without any validation.

2021-07-12 06:01 UTC, mint-chocolate-frappuccino commented on deploy/001_deploy_master_barista.ts
> +  // LatteVault
ok

2021-07-12 06:02 UTC, mint-chocolate-frappuccino commented on deploy/S001_timelock_add_pool_to_master_barista.ts
> +  if (!verifyStakingTokenAddress(allAvailableStakingToken, STAKING_TOKEN_ADDRESS)) throw new Error('verifyStakingTokenAddress:: not found')
that's unfortunated, ok

2021-07-13 05:11 UTC, coco-coke-kub approved these changes

2021-07-13 05:58 UTC, merged